<?php echo $this->render('html/header.php');?>
        <div id="content-box">
            <div class="border">
                <div class="padding">

                    <?php echo $this->layout()->content;?>


                    <div class="clr"></div>
                </div>
                <div class="clr"></div>
            </div>
        </div>
 <?php echo $this->render('html/footer.php');?>      
