<!DOCTYPE html>
<html lang="en">
<head>
	
		<?php echo $this->headTitle()?>
       	<?php echo $this->headMeta()?>
		<?php echo $this->headLink()?>
	
	<!--[if lt IE 7 ]>
	<link id="ie-style" href="css/style-ie.css" rel="stylesheet">
	<![endif]-->
	<!--[if IE 8 ]>
	<link id="ie-style" href="css/style-ie.css" rel="stylesheet">
	<![endif]-->
	<!--[if IE 9 ]>
	<![endif]-->	
	<!-- end: CSS -->
	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- start: Favicon -->
	<link rel="shortcut icon" href="img/favicon.ico">
	<!-- end: Favicon -->
			<style type="text/css">
			body { background: url(<?php echo $this->imgUrl?>/bg-login.jpg) !important; }
		</style>
		
			
</head>

<body>
 <?php echo $this->layout()->content;?>
<?php  echo $this->headScript()?>
	<!-- end: JavaScript-->
</body>
</html>
 